version: '3'
services:
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    environment:
      APP_NAME: php-fpm
    volumes:
      - .:/var/www/
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/logs:/var/log/nginx

  php-fpm:
    build:
      context: ./Docker/php-fpm
    volumes:
      - .:/var/www
      - ./Docker/app/php.ini:/usr/local/etc/php/custom.d
